In [ ]:
'''
EXPERIMENT 2 : IMPLEMENTATION OF QUEUE LEARNING- SOLVE THE FROZEN LAKE ENVIRONMENT USING QUEUE LEARNING EXPERIMENT WITH DIFFERENT LEARNING RATES DISCOUNT FACTORS AND EXPLORATION STRATEGIES USING EPISILON GREEDY METHOD
#queue- learning is a model free reinforcement learning algorithm that enables N gent to learn the best actions to take in an environment by interacting with it and maximising the cumilative rewards over time
'''

'\nEXPERIMENT 2 : IMPLEMENTATION OF QUEUE LEARNING- SOLVE THE FROZEN LAKE ENVIRONMENT USING QUEUE LEARNING EXPERIMENT WITH DIFFERENT LEARNING RATES DISCOUNT FACTORS AND EXPLORATION STRATEGIES USING EPISILON GREEDY METHOD \n#queue- learning is a model free reinforcement learning algorithm that enables N gent to learn the best actions to take in an environment by interacting with it and maximising the cumilative rewards over time \n'

In [ ]:
'''
LEARNING PARAMETERS :
  1. LEARNING RATE (ALPHA)-->controls how much new information overrides old information
                          --> learning rate 0 represents agent never learns new information
                          --> if the learnin grate is 1 then the agent completely overrides the old information with new information for each step.
                          --> low alpha represents a stable but slow learning while high alphs value represents a fast but potentially unstable learning pace
  2. DISCoUNT FACTOR (GAMMA)--> discount factor contorls how much future rewards matter compared to immidiate rewards.
                            --> discount factor 0 represents agent caring only about immidiate rewards.
                            --> discount factor 1 represents agent considering long term rewards as equally important as immidiate ones.
  3. EXLORATION PARAMETERS( EPISILON GREEDY STRATEGY):
                            --> EPISILON =1
                            --> INITIAL EXPLORATION RATE: PROBABILITY OF TAKING A RANDOM ACTION INSTEAD OF BEST KNOWN ONE
                            --> starts fully random action so that the agent explores the environment thouroughly.
                            --> highest possible exploration rate = minimum episilon =0.1
                            -->lowest possible exploration rate = nearly pure episilon
                            --> episilon_dk =0.001 --> controls how quickly the agent shifts from exploration to exploitation overtime.
                            --> larger dk represents faster convergence but risk of mising optimal paths are high
                            --. smaller dk represents smaller convergence but better exploration.

In [ ]:
import gymnasium as gym
import numpy as np
import time
import os

# Create FrozenLake environment
env = gym.make("FrozenLake-v1", render_mode="ansi", is_slippery=True)

# Parameters
num_episodes = 2000
max_steps_per_episode = 100
learning_rate = 0.1  # alpha
discount_factor = 0.99  # gamma
epsilon = 1.0  # exploration rate
max_epsilon = 1.0
min_epsilon = 0.01
epsilon_decay = 0.001

# Q-table
state_size = env.observation_space.n
action_size = env.action_space.n
Q = np.zeros((state_size, action_size))

# Training loop
for episode in range(num_episodes):
    state, _ = env.reset()
    done = False
    total_rewards = 0

    for step in range(max_steps_per_episode):
        # Epsilon-greedy strategy
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q[state, :])

        new_state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        # Q-learning update
        Q[state, action] = Q[state, action] + learning_rate * (
            reward + discount_factor * np.max(Q[new_state, :]) - Q[state, action]
        )

        state = new_state
        total_rewards += reward

        # Render environment in terminal
        os.system('cls' if os.name == 'nt' else 'clear')
        print(f"Episode: {episode+1}/{num_episodes} | Step: {step+1}")
        print(env.render())
        print(f"Reward this step: {reward}")
        print(f"Total rewards so far: {total_rewards}")
        print(f"Epsilon: {epsilon:.4f}")
        print(f"Q-table:\n{Q}")
        time.sleep(0.05)  # slow down for visibility

        if done:
            break

    # Decay epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-epsilon_decay * episode)

# Testing after training
print("\nTraining finished!\n")
print(f"Final Q-table:\n{Q}")

# Run one test episode
print("\nRunning a test episode...")
state, _ = env.reset()
done = False
total_rewards = 0

for step in range(max_steps_per_episode):
    action = np.argmax(Q[state, :])
    new_state, reward, terminated, truncated, info = env.step(action)
    time.sleep(0.5)
    state = new_state
    total_rewards += reward
    if terminated or truncated:
        print("Test episode ended.")
        break

env.close()

Streaming output truncated to the last 5000 lines.
 [0.         0.         0.         0.        ]
 [0.41538478 0.42167481 0.4122536  0.56868811]
 [0.31778817 0.62046085 0.41131228 0.32192724]
 [0.59751955 0.37100907 0.41494713 0.32360092]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.44243482 0.39615367 0.76815496 0.51121379]
 [0.64178566 0.82004523 0.74802235 0.83856802]
 [0.         0.         0.         0.        ]]
Episode: 1991/2000 | Step: 3
  (Left)
SFFF
FHFH
FFFH
HFFG

Reward this step: 0.0
Total rewards so far: 0.0
Epsilon: 0.1455
Q-table:
[[0.51296722 0.47403399 0.47359573 0.46769539]
 [0.32731778 0.21290166 0.29228849 0.42526049]
 [0.33529598 0.26492148 0.25380172 0.28473022]
 [0.02675988 0.11060271 0.03403191 0.30485952]
 [0.52780988 0.37968597 0.33569729 0.32058352]
 [0.         0.         0.         0.        ]
 [0.20322536 0.17434651 0.32216864 0.08861353]
 [0.         0.         0.         0.        ]
 [0.41538478 0.42